# QUARKUS CONFIG
quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orderdb
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.order-events-out.connector=smallrye-kafka
mp.messaging.outgoing.order-events-out.topic=order-events
mp.messaging.outgoing.order-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.order-notifications-in.connector=smallrye-kafka
mp.messaging.incoming.order-notifications-in.topic=order-notifications
mp.messaging.incoming.order-notifications-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.order-notifications-in.group.id=order-api-group
mp.messaging.incoming.order-notifications-in.auto.offset.reset=earliest
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
mp.openapi.extensions.smallrye.info.title=Order API
mp.openapi.extensions.smallrye.info.version=1.0.0
quarkus.smallrye-health.root-path=/health
quarkus.log.level=INFO
quarkus.log.category."com.example".level=DEBUG

# H2 Console
quarkus.h2.console.enabled=true
